version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev --db=postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
    networks:
      - keycloak-network
  keycloak-db:
    image: postgres
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:

volumes:
  keycloak_db_data: